spring:
  application:
    name: order
  redis:
    host: wx.myzf.xyz
    password: Woainia123
  rabbitmq:
    host: wx.myzf.xyz
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  test4
girl:
  age: 20
  name: lili
